/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rachel Avina 628972
 */
public class BalancingAct extends javax.swing.JFrame {

    String[] reactantOne;
    String[] reactantTwo;
    String[] productOne;
    
    int rand;
    
    int numRuns;
    int[] dontRepeat;
    int numsPulled;
    
    int[] coefficient1;
    int[] coefficient2;
    int[] coefficient3;
    int answerCoOne;
    int answerCoTwo;
    int answerCoThree;
    int[] formula1;
    int[] formula2;
    int[] formula3;
    int form1;
    int form2;
    int form3;
    int[] oxidation1;
    int[] oxidation2;
    int[] oxidation3;
    int ox1;
    int ox2;
    int ox3;
    
    int correct;
    int incorrect;
    
    boolean coefficient;
    
    //String productTwo [];
    
    /**
     * Creates new form BalancingAct
     */
    public BalancingAct() {
        initComponents();
    
       
    
    
    
       
       

    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputBox1 = new javax.swing.JTextField();
        inputBox2 = new javax.swing.JTextField();
        inputBox3 = new javax.swing.JTextField();
        inputBox5 = new javax.swing.JTextField();
        inputBox6 = new javax.swing.JTextField();
        inputBox7 = new javax.swing.JTextField();
        inputBox8 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        inputbox11 = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        inputbox9 = new javax.swing.JTextField();
        inputbox10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        outputbox12 = new javax.swing.JTextField();
        outputbox13 = new javax.swing.JTextField();
        outputbox14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Balancing Chemistry Equations");

        inputBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox1ActionPerformed(evt);
            }
        });

        inputBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox2ActionPerformed(evt);
            }
        });

        inputBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox3ActionPerformed(evt);
            }
        });

        inputBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox5ActionPerformed(evt);
            }
        });

        inputBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox6ActionPerformed(evt);
            }
        });

        inputBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox7ActionPerformed(evt);
            }
        });

        inputBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox8ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("Text will output here");

        button2.setText("Submit");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label7.setText("How many equations do you want?");

        inputbox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbox11ActionPerformed(evt);
            }
        });

        button1.setText("Submit");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        inputbox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbox9ActionPerformed(evt);
            }
        });

        inputbox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbox10ActionPerformed(evt);
            }
        });

        jLabel3.setText("Oxidation Numbers:");

        outputbox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputbox12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(button2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputbox11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(inputbox9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(outputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(inputBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputbox13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addComponent(inputBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputbox10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(outputbox14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)))
                                .addComponent(inputBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputbox11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputbox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputbox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(button2)
                .addGap(18, 18, 18)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox1ActionPerformed
        int answerCoOne = Integer.parseInt(inputBox1.getText());
        
        
        //make array for coefficent
        
        
        
        
        
    }//GEN-LAST:event_inputBox1ActionPerformed

    private void inputBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox2ActionPerformed
        int answerCoTwo = Integer.parseInt(inputBox2.getText());
        
    }//GEN-LAST:event_inputBox2ActionPerformed

    private void inputBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox3ActionPerformed
        int answerCoThree = Integer.parseInt(inputBox3.getText());
        
    }//GEN-LAST:event_inputBox3ActionPerformed

    private void inputBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox5ActionPerformed
        int form1 = Integer.parseInt(inputBox5.getText());
        
    }//GEN-LAST:event_inputBox5ActionPerformed

    private void inputBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox6ActionPerformed
        int form2 = Integer.parseInt(inputBox6.getText());
        
    }//GEN-LAST:event_inputBox6ActionPerformed

    private void inputBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox7ActionPerformed
        int form3 = Integer.parseInt(inputBox7.getText());
        
    }//GEN-LAST:event_inputBox7ActionPerformed

    private void inputBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox8ActionPerformed
        int ox1 = Integer.parseInt(inputBox8.getText());
        
    }//GEN-LAST:event_inputBox8ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        System.out.println("second button pushed");

        int [] coefficient1 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] coefficient2 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] coefficient3 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] formula1 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] formula2 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] formula3 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] oxidation1 = {
            1,
            2,
            3,
            4,
            5
        };
        
        int [] oxidation2 = {
            1,
            2,
            3,
            4,
            5
        };
         
        int [] oxidation3 = {
            1,
            2,
            3,
            4,
            5
        };
        
        //for (int i = 0; i < 10; i++) { // change the second parameter
            System.out.println("methods next");
            /*String co = coefficientCheck(coefficient);
            if (coefficientCheck(coefficient) == true) {
            System.out.println("coefficient confirmed");
            }
            else    {
                System.out.println("coefficient failed");
            }
            System.out.println("coefficient Check run");
            formulaCheck(rand);
            oxidationCheck(rand);
            if (coefficientCheck(coefficient) == true && formulaCheck(rand) == true && oxidationCheck(rand) == true )   {
                correct++;
                System.out.println("correct");
            }
            else    {
                incorrect++;
                System.out.println("incorrect");
            } */
            
            String coefficient5 = coefficientCheck();
            
            String outputText = "" + coefficient5;
            System.out.println(outputText);
            
            
            
            
        //}
        
        
        //might have to make methods and call them at once similar to communiations
        
            
        
        
    }//GEN-LAST:event_button2ActionPerformed

    private void outputbox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputbox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputbox12ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       
        
        //for (int i = 0; i < numRuns; i++)   {
        
        int rand = (int) (Math.random() * 5) + 1; // have to change the five, I had numRuns but I don't know
        
         String [] reactantOne = {
            "Fe",
            "Ni",
            "Pb",
            "K",
            "H"
        };
        
        String [] reactantTwo = {
           "O",
           "Fl",
           "N",
           "Cl",
           "C"
        };
       
        String [] productOne = {
            "result1",
            "result2",
            "result3",
            "result4",
            "result5"
        };    
       
        
        
       dontRepeat = new int[reactantOne.length];
       numsPulled = 0;
       

        //for loop here? could just add to rand each time and start at a new random place every time
       
        isRepeated(rand);
        if (isRepeated(rand) == true) {
            //rand = (int) (Math.random() * 5) +1;
            System.out.println("wrong");
        }
        else    {
        outputbox12.setText(reactantOne[rand]);
        outputbox13.setText(reactantTwo[rand]);
        outputbox14.setText(productOne[rand]); 
        System.out.println("nums printed");
        }
        
        
       
        
        
        //}
       
       
       
        
    }//GEN-LAST:event_button1ActionPerformed

    private void inputbox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbox11ActionPerformed
        int numRuns = Integer.parseInt(inputbox11.getText());
        
    }//GEN-LAST:event_inputbox11ActionPerformed

    private void inputbox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbox9ActionPerformed
        int ox2 = Integer.parseInt(inputbox9.getText());
        
    }//GEN-LAST:event_inputbox9ActionPerformed

    private void inputbox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbox10ActionPerformed
        int ox3 = Integer.parseInt(inputbox10.getText());
        
        
    }//GEN-LAST:event_inputbox10ActionPerformed

    
    
    private boolean isRepeated(int rand) {
        boolean repeat = dontRepeat.length > rand;
        for (int i = 0; i < dontRepeat.length; i++) {
            if (rand == dontRepeat[i]) {
                return true;
            }
            else    {
                return false;
            }
        }
        
        return repeat;
    }
    
    /*public boolean coefficientCheck(boolean coefficient)  {
        //boolean coefficient = rand > 1; // check these booleans
        if (answerCoOne == coefficient1[rand] && answerCoTwo == coefficient2[rand] && answerCoThree == coefficient3[rand]) {
               coefficient = true;  
            }
            
            else    {
                coefficient = false;
            }
        return coefficient;
    }*/
    
    
    public String coefficientCheck()    {
        String output;
        if (answerCoOne == coefficient1[rand] ) {
            output = "correct";
        }
        else    {
            output = "incorrect";
        }
        return output;
    }
    
    
    
    
    public boolean formulaCheck (int rand) {
        //boolean formula = rand > 1;
        if (form1 == formula1[rand] && form2 == formula2[rand] && form3 == formula3[rand]) {
                return true;
            }
        
            else    {
            //label2.setText("That's incorrect, try checking the formula numbers.");
            return false;
            }
        //return formula;
    }
    
    public boolean oxidationCheck (int rand)   {
        //boolean oxidation = rand > 1;
        if (ox1 == oxidation1[rand] && ox2 == oxidation2[rand] && ox3 == oxidation3[rand]) {
                return true;
        }
            else    {
            //label2.setText("That's incorrect, try checking the oxidation numbers.");
            return false;
            
        }
        //return oxidation;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalancingAct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JTextField inputBox1;
    private javax.swing.JTextField inputBox2;
    private javax.swing.JTextField inputBox3;
    private javax.swing.JTextField inputBox5;
    private javax.swing.JTextField inputBox6;
    private javax.swing.JTextField inputBox7;
    private javax.swing.JTextField inputBox8;
    private javax.swing.JTextField inputbox10;
    private javax.swing.JTextField inputbox11;
    private javax.swing.JTextField inputbox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField outputbox12;
    private javax.swing.JTextField outputbox13;
    private javax.swing.JTextField outputbox14;
    // End of variables declaration//GEN-END:variables
}
