/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rachel Avina 628972
 */
public class BalancingAct extends javax.swing.JFrame {

    String[] reactantOne;
    String[] reactantTwo;
    String[] productOne;
    
    int rand;
    
    String[] coefficient1;
    String[] coefficient2;
    String[] coefficient3;
    String answerCoOne;
    String answerCoTwo;
    String answerCoThree;
    String[] formula1;
    String[] formula2;
    String[] formula3;
    String[] formula4;
    String form1;
    String form2;
    String form3;
    String form4;
    String[] oxidation1;
    String[] oxidation2;
    String[] oxidation3;
    String [] oxidation4;
    String ox1;
    String ox2;
    String ox3;
    String ox4;
    
    int correct;
    int incorrect;

    int score = 0;
    int repeat[];
   
    int runs = 0;
    
    /**
     * Creates new form BalancingAct
     */
    public BalancingAct() {
        initComponents();
        
        repeat = new int [20];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputBox1 = new javax.swing.JTextField();
        inputBox2 = new javax.swing.JTextField();
        inputBox3 = new javax.swing.JTextField();
        inputBox5 = new javax.swing.JTextField();
        inputBox6 = new javax.swing.JTextField();
        inputBox7 = new javax.swing.JTextField();
        inputBox8 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        label7 = new javax.swing.JLabel();
        inputbox9 = new javax.swing.JTextField();
        inputbox10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        outputbox12 = new javax.swing.JTextField();
        outputbox13 = new javax.swing.JTextField();
        outputbox14 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        inputbox12 = new javax.swing.JTextField();
        inputbox11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("Balancing Chemistry Equations");

        inputBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox1ActionPerformed(evt);
            }
        });

        inputBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox2ActionPerformed(evt);
            }
        });

        inputBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox3ActionPerformed(evt);
            }
        });

        inputBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox5ActionPerformed(evt);
            }
        });

        inputBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox6ActionPerformed(evt);
            }
        });

        inputBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox7ActionPerformed(evt);
            }
        });

        inputBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBox8ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        label2.setText("Score: ");

        button2.setText("Submit");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        label7.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        label7.setText("Hit the button for a new random equation.");

        inputbox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbox9ActionPerformed(evt);
            }
        });

        inputbox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbox10ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel3.setText("Remember to put positive and negative signs with the oxidation numbers");

        outputbox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputbox12ActionPerformed(evt);
            }
        });

        jLabel2.setText("+");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText(" →");

        submit.setText("New Equation");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chemistrybeaker1.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chemistrybeaker3.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addComponent(inputBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputbox13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(inputbox9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(button2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116)))
                .addComponent(inputbox10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputbox11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(inputBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(outputbox14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputbox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputbox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputbox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(outputbox13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputbox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addGap(56, 56, 56)
                .addComponent(button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox1ActionPerformed
   
    }//GEN-LAST:event_inputBox1ActionPerformed

    private void inputBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox2ActionPerformed
 
    }//GEN-LAST:event_inputBox2ActionPerformed

    private void inputBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox3ActionPerformed
   
    }//GEN-LAST:event_inputBox3ActionPerformed

    private void inputBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox5ActionPerformed
    
    }//GEN-LAST:event_inputBox5ActionPerformed

    private void inputBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox6ActionPerformed
   
    }//GEN-LAST:event_inputBox6ActionPerformed

    private void inputBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox7ActionPerformed
        
    }//GEN-LAST:event_inputBox7ActionPerformed

    private void inputBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBox8ActionPerformed
  
    }//GEN-LAST:event_inputBox8ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        secondPush();
         if (secondPush() == true) {
          score +=  10;   
          label2.setText("Score: " + score);
         }
         else   {
             score -= 10;
             label2.setText("Score: " + score);
         }
        
        
    }//GEN-LAST:event_button2ActionPerformed
    
    private void outputbox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputbox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputbox12ActionPerformed

    private void inputbox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbox9ActionPerformed
        
    }//GEN-LAST:event_inputbox9ActionPerformed

    private void inputbox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbox10ActionPerformed
        
    }//GEN-LAST:event_inputbox10ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
            firstPush();    
    }//GEN-LAST:event_submitActionPerformed

    public String firstPush()   {

        
         String [] reactantOne = {
            "Na",
            "H",
            "H",
            "Al",
            "Fe",
            "K",
            "NO",
            "Mg",
            "Al",
            "CO",
            "Na",
            "Ra",
            "Pb",
            "S",
            "Si",
            "Zn",
            "Al",
            "Sn",
            "Li",
            "Be"
        };
        
        String [] reactantTwo = {
           "Cl",
           "O",
           "N",
           "O",
           "S",
           "Cl",
           "O",
           "O",
           "Br",
           "O",
           "O",
           "Cl",
           "I",
           "O",
           "Cl",
           "O",
           "Br",
           "O",
           "F",
           "O"
        };
       
        String [] productOne = {
            "NaCl",
            "HO",
            "NH",
            "AlO",
            "FeS",
            "KCl",
            "NO",
            "MgO",
            "AlBr",
            "CO",
            "NaO",
            "RaCl",
            "PbI",
            "SO",
            "SiCl",
            "ZnO",
            "AlBr",
            "SnO",
            "LiF",
            "BeO"
        }; 
        
        
        rand = (int) (Math.random() * 20);
        
        while (isRepeated())   {
            rand = (int) (Math.random() * 20);
        }
              outputbox12.setText(reactantOne[rand]);
              outputbox13.setText(reactantTwo[rand]);
              outputbox14.setText(productOne[rand]);   
        repeat[runs] = rand;
        runs++;
        String r = "r";
        return r;
    }
    
    
    public boolean secondPush ()    {
        
        String [] coefficient1 = {
            "2",
            "2",
            "3",
            "4",
            "8",
            "2",
            "2",
            "2",
            "2",
            "2",
            "4",
            "1",
            "1",
            "2",
            "1",
            "2",
            "2",
            "1",
            "2",
            "1"
        };
        
        String [] coefficient2 = {
            "1",
            "1",
            "1",
            "3",
            "1",
            "1",
            "1",
            "1",
            "3",
            "1",
            "1",
            "1",
            "1",
            "3",
            "1",
            "1",
            "3",
            "1",
            "1",
            "1"
        };
        
        String [] coefficient3 = {
            "2",
            "2",
            "2",
            "2",
            "8",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "1",
            "1",
            "2",
            "1",
            "2",
            "2",
            "1",
            "2",
            "1"
        };
        
        String [] formula1 = {
            "1",
            "2",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1"
        };
        
        String [] formula2 = {
            "2",
            "2",
            "2",
            "2",
            "8",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "2",
            "1"
        };
        
        String [] formula3 = {
            "1",
            "2",
            "1",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "2",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1"
        };
        
        String [] formula4 = {
            "1",
            "1",
            "3",
            "3",
            "1",
            "1",
            "2",
            "1",
            "3",
            "2",
            "1",
            "2",
            "2",
            "3",
            "2",
            "1",
            "3",
            "2",
            "1",
            "1"
        };
        
        String [] oxidation1 = {
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        };
        
        String [] oxidation2 = {
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0"
        };
         
        String [] oxidation3 = {
            "+1",
            "+1",
            "-3",
            "+3",
            "+2",
            "+1",
            "+4",
            "+2",
            "+3",
            "+4",
            "+1",
            "+2",
            "+2",
            "+6",
            "+2",
            "+2",
            "+3",
            "+4",
            "+1",
            "+2"
        };
        
        String [] oxidation4 = {
            "-2",
            "-2",
            "+1",
            "-2",
            "-1",
            "-1",
            "-2",
            "-1",
            "-1",
            "-2",
            "-2",
            "-1",
            "-1",
            "-2",
            "-1",
            "-2",
            "-1",
            "-2",
            "-1",
            "-2"
        };
        
        answerCoOne = inputBox1.getText();
        answerCoTwo = inputBox2.getText();
        answerCoThree = inputBox3.getText();
        form1 = inputBox5.getText();
        form2 = inputBox6.getText();
        form3 = inputbox12.getText();
        form4 = inputBox7.getText();
        ox1 = inputBox8.getText();
        ox2 = inputbox9.getText();
        ox3 = inputbox10.getText();  
        ox4 = inputbox11.getText();

            
            if (answerCoOne.equals(coefficient1[rand]) && answerCoTwo.equals(coefficient2[rand]) && answerCoThree.equals(coefficient3[rand]) && form1.equals(formula1[rand]) && form2.equals(formula2[rand]) && form3.equals(formula3[rand]) && form4.equals(formula4[rand]) && ox1.equals(oxidation1[rand]) && ox2.equals(oxidation2[rand]) && ox3.equals(oxidation3[rand]) && ox4.equals(oxidation4[rand])) {
               correct++;
               return true;
            }
            
            else    {
                incorrect++;
                return false;
            }    
    }
    
    public boolean isRepeated() {
         for (int i = 0; i < runs; i++) {
            if (repeat[i] == rand) {
                System.out.println("Catch");
             return true;   
                }
            }
         return false;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalancingAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalancingAct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button2;
    private javax.swing.JTextField inputBox1;
    private javax.swing.JTextField inputBox2;
    private javax.swing.JTextField inputBox3;
    private javax.swing.JTextField inputBox5;
    private javax.swing.JTextField inputBox6;
    private javax.swing.JTextField inputBox7;
    private javax.swing.JTextField inputBox8;
    private javax.swing.JTextField inputbox10;
    private javax.swing.JTextField inputbox11;
    private javax.swing.JTextField inputbox12;
    private javax.swing.JTextField inputbox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField outputbox12;
    private javax.swing.JTextField outputbox13;
    private javax.swing.JTextField outputbox14;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
